default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_app_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: api_app_test
  host: db
  username: postgres
  password: password

production:
  <<: *default
  database: api_app_production
  username: api_app
  password: <%= ENV["API_APP_DATABASE_PASSWORD"] %>
